/**
 * https://github.com/kriasoft/react-starter-kit/pull/1132
 */
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import hoistStatics from 'hoist-non-react-statics';

/**
 * Insert StyleSheet object generated by `inline-css-loader` into DOM
 */
let cache;
function insertCss({ id, cssText }, update) {
  if (!cache) {
    cache = {};
    [...document.head.getElementsByTagName('style')].forEach(elem => {
      const dataId = elem.getAttribute('data-id');
      if (dataId) {
        cache[dataId] = { count: 0, elem, cssText: elem.textContent };
      }
    });
  }

  let inserted = cache[id];
  if (!inserted) {
    inserted = { count: 0, elem: null, cssText };
    cache[id] = inserted;
  }

  if (!inserted.elem) {
    const elem = document.createElement('style');
    inserted.elem = elem;
    elem.setAttribute('data-id', id);
    elem.textContent = cssText;
    document.head.appendChild(elem);
  } else if (inserted.cssText !== cssText) {
    inserted.cssText = cssText;
    inserted.elem.textContent = cssText;
  }

  if (!update) {
    inserted.count += 1;
  }

  // Prevent flash of unstyled content (FOUC)
  return () =>
    window.setTimeout(() => {
      inserted.count -= 1;
      if (inserted.count <= 0 && inserted.elem) {
        inserted.elem.parentNode.removeChild(inserted.elem);
        inserted.elem = null;
      }
    }, 0);
}

function withStyles(...styles) {
  return function wrapWithStyles(ComposedComponent) {
    class WithStyles extends Component {
      componentWillMount() {
        // Server side
        if (this.context.insertCss) {
          this.inserted = [];
          styles.forEach(s => this.context.insertCss(s));

          // Client side
        } else {
          this.inserted = styles.map(s => insertCss(s.getCss()));
        }
      }

      componentWillUnmount() {
        this.inserted.forEach(remove => remove());
      }

      render() {
        return <ComposedComponent {...this.props} />;
      }
    }

    // Enable Hot Module Replacement (HMR)
    if (module.hot) {
      WithStyles.prototype.componentWillReceiveProps = function componentWillReceiveProps() {
        this.inserted = styles.map(s => insertCss(s.getCss(), true));
      };
    }

    const displayName =
      ComposedComponent.displayName || ComposedComponent.name || 'Component';

    WithStyles.displayName = `WithStyles(${displayName})`;
    WithStyles.contextTypes = { insertCss: PropTypes.func };
    WithStyles.ComposedComponent = ComposedComponent;

    return hoistStatics(WithStyles, ComposedComponent);
  };
}

export default withStyles;
